# Let's not reinvent the wheel
FROM timhaak/plex:latest

# Replace the Transcoder binary with our elastic transcoder
ADD ["./plex-elastic-transcoder", "/usr/lib/plexmediaserver/Resources/Plex New Transcoder"]
