# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "promote"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "todaywasawesome/kube-plex"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  geterdone:
    title: "Build and Test"
    type: parallel
    stage: "build"
    steps:
      build:
        title: "Building Docker image"
        type: "build"
        image_name: "todaywasawesome/kube-plex"
        working_directory: "${{clone}}"
        tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
        dockerfile: "Dockerfile"
        stage: "build"
    
  push:
    type: push
    arguments:
      candidate: '${{build}}'
      tag: latest
      image_name: "todaywasawesome/kube-plex"
      registry: todaywasawesome
    stage: "promote"

