apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-tcp
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.serviceTCP.labels }}
{{ toYaml .Values.serviceTCP.labels | indent 4 }}
{{- end }}
{{- with .Values.serviceTCP.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if (or (eq .Values.serviceTCP.type "ClusterIP") (empty .Values.serviceTCP.type)) }}
  type: ClusterIP
  {{- if .Values.serviceTCP.clusterIP }}
  clusterIP: {{ .Values.serviceTCP.clusterIP }}
  {{end}}
{{- else if eq .Values.serviceTCP.type "LoadBalancer" }}
  type: {{ .Values.serviceTCP.type }}
  {{- if .Values.serviceTCP.loadBalancerIP }}
  loadBalancerIP: {{ .Values.serviceTCP.loadBalancerIP }}
  {{- end }}
  {{- if .Values.serviceTCP.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.serviceTCP.loadBalancerSourceRanges | indent 4 }}
  {{- end -}}
{{- else }}
  type: {{ .Values.serviceTCP.type }}
{{- end }}
{{- if .Values.serviceTCP.externalIPs }}
  externalIPs:
{{ toYaml .Values.serviceTCP.externalIPs | indent 4 }}
{{- end }}
  {{- if .Values.serviceTCP.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.serviceTCP.externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: pms
      port: {{ .Values.serviceTCP.port }}
      protocol: TCP
      targetPort: pms
{{ if (and (eq .Values.serviceTCP.type "NodePort") (not (empty .Values.serviceTCP.nodePort))) }}
      nodePort: {{.Values.serviceTCP.nodePort}}
{{ end }}
    - name: http
      port: 80
      targetPort: pms
    - name: https
      port: 443
      targetPort: https
    - name: plex-dlna
      port: 1900
      targetPort: plex-dlna
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
