apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-udp
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.serviceUDP.labels }}
{{ toYaml .Values.serviceUDP.labels | indent 4 }}
{{- end }}
{{- with .Values.serviceUDP.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if (or (eq .Values.serviceUDP.type "ClusterIP") (empty .Values.serviceUDP.type)) }}
  type: ClusterIP
  {{- if .Values.serviceUDP.clusterIP }}
  clusterIP: {{ .Values.serviceUDP.clusterIP }}
  {{end}}
{{- else if eq .Values.serviceUDP.type "LoadBalancer" }}
  type: {{ .Values.serviceUDP.type }}
  {{- if .Values.serviceUDP.loadBalancerIP }}
  loadBalancerIP: {{ .Values.serviceUDP.loadBalancerIP }}
  {{- end }}
  {{- if .Values.serviceUDP.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.serviceUDP.loadBalancerSourceRanges | indent 4 }}
  {{- end -}}
{{- else }}
  type: {{ .Values.serviceUDP.type }}
{{- end }}
{{- if .Values.serviceUDP.externalIPs }}
  externalIPs:
{{ toYaml .Values.serviceUDP.externalIPs | indent 4 }}
{{- end }}
  {{- if .Values.serviceUDP.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.serviceUDP.externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: plex-dlna-udp
      port: 1900
      protocol: UDP
      targetPort: plex-dlna-udp
    - name: plex-gdm1
      port: 32410
      protocol: UDP
      targetPort: plex-gdm1
    - name: plex-gdm2
      port: 32412
      protocol: UDP
      targetPort: plex-gdm2
    - name: plex-gdm3
      port: 32413
      protocol: UDP
      targetPort: plex-gdm3
    - name: plex-gdm4
      port: 32414
      protocol: UDP
      targetPort: plex-gdm4
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
