apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: plextranscodejobs.plex.tv
spec:
  group: plex.tv
  names:
    kind: PlexTranscodeJob
    listKind: PlexTranscodeJobList
    plural: plextranscodejobs
    singular: plextranscodejob
    shortNames:
    - ptj
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            args:
              description: An array of arguments to pass to the real plex transcode
                binary
              items:
                type: string
              type: array
            cwd:
              type: string
            env:
              items:
                type: string
              type: array
          required:
          - args
          - env
          - cwd
          type: object
        status:
          properties:
            error:
              type: string
            state:
              description: 'The state of the job, one of: CREATED ASSIGNED STARTED
                FAILED COMPLETED'
              type: string
            transcoder:
              description: Name of the transcoder pod assigned the transcode job
              type: string
          required:
          - transcoder
          - state
          - error
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
