/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1

import (
	time "time"

	ptj_v1 "github.com/munnerz/kube-plex/pkg/apis/ptj/v1"
	versioned "github.com/munnerz/kube-plex/pkg/client/clientset/versioned"
	internalinterfaces "github.com/munnerz/kube-plex/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/munnerz/kube-plex/pkg/client/listers/ptj/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PlexTranscodeJobInformer provides access to a shared informer and lister for
// PlexTranscodeJobs.
type PlexTranscodeJobInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.PlexTranscodeJobLister
}

type plexTranscodeJobInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPlexTranscodeJobInformer constructs a new informer for PlexTranscodeJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPlexTranscodeJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPlexTranscodeJobInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPlexTranscodeJobInformer constructs a new informer for PlexTranscodeJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPlexTranscodeJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PlextranscodejobsV1().PlexTranscodeJobs(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PlextranscodejobsV1().PlexTranscodeJobs(namespace).Watch(options)
			},
		},
		&ptj_v1.PlexTranscodeJob{},
		resyncPeriod,
		indexers,
	)
}

func (f *plexTranscodeJobInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPlexTranscodeJobInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *plexTranscodeJobInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&ptj_v1.PlexTranscodeJob{}, f.defaultInformer)
}

func (f *plexTranscodeJobInformer) Lister() v1.PlexTranscodeJobLister {
	return v1.NewPlexTranscodeJobLister(f.Informer().GetIndexer())
}
